export const START_MONITOR_REQUEST = 'START_MONITOR_REQUEST';
export type START_MONITOR_REQUEST = typeof START_MONITOR_REQUEST;

export const START_MONITOR_FAILURE = 'START_MONITOR_FAILURE';
export type START_MONITOR_FAILURE = typeof START_MONITOR_FAILURE;

export const START_MONITOR_SUCCESS = 'START_MONITOR_SUCCESS';
export type START_MONITOR_SUCCESS = typeof START_MONITOR_SUCCESS;

export const STOP_MONITOR = 'STOP_MONITOR';
export type STOP_MONITOR = typeof STOP_MONITOR;
